// Country reference data — static data extracted from app.js so the frequently-updated
// code file stays smaller (incremental updates ship only what changed).
// Loaded before app.js; exposed on window.AppStaticData.
window.AppStaticData = window.AppStaticData || {};
window.AppStaticData.BUILTIN_COUNTRY_LINKS = [
    { cc: "AL", label: "Observation.org", url: "https://al.observation.org/" },
    { cc: "AL", label: "Albanian Ornithological Society", url: "https://aos-alb.org/" },
    { cc: "AL", label: "PPNEA", url: "https://ppnea.org/" },
    { cc: "AD", label: "ornitho.ad", url: "https://www.ornitho.ad/" },
    { cc: "AD", label: "Andorra Research + Innovation: Ornitho", url: "https://www.ari.ad/en/projects/ornitho" },
    { cc: "AM", label: "Armenian Bird Census", url: "https://armenian-bird-census.weebly.com/" },
    { cc: "AM", label: "FPWC", url: "https://www.fpwc.org/" },
    { cc: "AM", label: "eBird", url: "https://ebird.org/region/AM" },
    { cc: "AT", label: "ornitho.at", url: "https://www.ornitho.at/" },
    { cc: "AT", label: "BirdLife Österreich", url: "https://www.birdlife.at/" },
    { cc: "AZ", label: "Azerbaijan Ornithological Society", url: "https://www.aos.az/" },
    { cc: "AZ", label: "Birding Azerbaijan", url: "https://birdingazerbaijan.org/" },
    { cc: "AZ", label: "eBird", url: "https://ebird.org/region/AZ" },
    { cc: "BY", label: "eBird", url: "https://ebird.org/region/BY" },
    { cc: "BY", label: "Observation.org", url: "https://by.observation.org/" },
    { cc: "BY", label: "Belarusian Bird Ringing Centre", url: "https://www.ringing.center/" },
    { cc: "BE", label: "Waarnemingen.be", url: "https://waarnemingen.be/" },
    { cc: "BE", label: "Observations.be", url: "https://observations.be/" },
    { cc: "BE", label: "Natuurpunt", url: "https://www.natuurpunt.be/" },
    { cc: "BE", label: "Natagora", url: "https://www.natagora.be/" },
    { cc: "BA", label: "Observation.org", url: "https://ba.observation.org/" },
    { cc: "BA", label: "Naše Ptice", url: "https://www.ptice.ba/" },
    { cc: "BA", label: "eBird", url: "https://ebird.org/region/BA" },
    { cc: "BG", label: "SmartBirds", url: "https://smartbirds.org/" },
    { cc: "BG", label: "BSPB", url: "https://bspb.org/en/" },
    { cc: "BG", label: "Atlas of Breeding Birds in Bulgaria", url: "https://atlas.bspb.org/en/" },
    { cc: "HR", label: "Fauna.hr", url: "https://fauna.hr/" },
    { cc: "HR", label: "BIOM", url: "https://www.biom.hr/en/" },
    { cc: "HR", label: "Bioportal Croatia", url: "https://bioportal.hr/en/" },
    { cc: "CY", label: "BirdLife Cyprus", url: "https://birdlifecyprus.org/" },
    { cc: "CY", label: "Record Your Sightings", url: "https://birdlifecyprus.org/guide-to-birdwatching/record-your-sightings/" },
    { cc: "CY", label: "eBird", url: "https://ebird.org/region/CY" },
    { cc: "CZ", label: "AVIF / Birds.cz", url: "https://avif.birds.cz/" },
    { cc: "CZ", label: "Czech Society for Ornithology", url: "https://www.birdlife.cz/" },
    { cc: "DK", label: "DOFbasen", url: "https://dofbasen.dk/" },
    { cc: "DK", label: "DOF BirdLife", url: "https://www.dof.dk/" },
    { cc: "DK", label: "Netfugl", url: "https://www.netfugl.dk/" },
    { cc: "EE", label: "eElurikkus", url: "https://elurikkus.ee/en" },
    { cc: "EE", label: "Estonian Ornithological Society", url: "https://www.eoy.ee/" },
    { cc: "EE", label: "PlutoF", url: "https://plutof.ut.ee/" },
    { cc: "FI", label: "Tiira", url: "https://www.tiira.fi/" },
    { cc: "FI", label: "BirdLife Finland", url: "https://www.birdlife.fi/" },
    { cc: "FI", label: "Laji.fi", url: "https://laji.fi/en" },
    { cc: "FR", label: "Faune-France", url: "https://www.faune-france.org/" },
    { cc: "FR", label: "LPO", url: "https://www.lpo.fr/" },
    { cc: "FR", label: "Oiseaux.net", url: "https://www.oiseaux.net/" },
    { cc: "GE", label: "SABUKO", url: "https://www.sabuko.org/en/" },
    { cc: "GE", label: "Batumi Raptor Count", url: "https://www.batumiraptorcount.org/" },
    { cc: "GE", label: "eBird", url: "https://ebird.org/region/GE" },
    { cc: "DE", label: "ornitho.de", url: "https://www.ornitho.de/" },
    { cc: "DE", label: "DDA", url: "https://www.dda-web.de/" },
    { cc: "DE", label: "NABU", url: "https://www.nabu.de/" },
    { cc: "GR", label: "eBird", url: "https://ebird.org/region/GR" },
    { cc: "GR", label: "Hellenic Ornithological Society", url: "https://ornithologiki.gr/en/" },
    { cc: "HU", label: "MAP", url: "https://map.mme.hu/" },
    { cc: "HU", label: "MME / BirdLife Hungary", url: "https://mme.hu/en" },
    { cc: "IS", label: "Fuglar.is", url: "https://fuglar.is/" },
    { cc: "IS", label: "Fuglavernd", url: "https://fuglavernd.is/" },
    { cc: "IS", label: "Natural Science Institute of Iceland: Birds", url: "https://www.ni.is/is/dyr/fuglar" },
    { cc: "IE", label: "BirdTrack", url: "https://www.bto.org/get-involved/volunteer/projects/birdtrack" },
    { cc: "IE", label: "BirdWatch Ireland", url: "https://birdwatchireland.ie/" },
    { cc: "IE", label: "IrishBirding", url: "https://www.irishbirding.com/" },
    { cc: "IE", label: "Irish Rare Birds Committee", url: "https://irbc.ie/" },
    { cc: "IT", label: "ornitho.it", url: "https://www.ornitho.it/" },
    { cc: "IT", label: "LIPU", url: "https://www.lipu.it/" },
    { cc: "IT", label: "CISO-COI", url: "https://ciso-coi.it/" },
    { cc: "KZ", label: "Birds of Kazakhstan", url: "https://kz.birding.day/" },
    { cc: "KZ", label: "ACBK", url: "https://www.acbk.kz/" },
    { cc: "KZ", label: "eBird", url: "https://ebird.org/region/KZ" },
    { cc: "XK", label: "Observation.org", url: "https://xk.observation.org/" },
    { cc: "XK", label: "Common Bird Monitoring in Kosovo", url: "https://observation.org/projects/101/" },
    { cc: "XK", label: "eBird", url: "https://ebird.org/region/XK" },
    { cc: "LV", label: "Dabas Dati", url: "https://dabasdati.ornitho.lv/" },
    { cc: "LV", label: "Latvian Ornithological Society", url: "https://www.lob.lv/" },
    { cc: "LV", label: "Latvian Fund for Nature", url: "https://ldf.lv/en/" },
    { cc: "LI", label: "ornitho.ch", url: "https://www.ornitho.ch/" },
    { cc: "LI", label: "BZG", url: "https://bzg.li/" },
    { cc: "LI", label: "Avibase Liechtenstein", url: "https://avibase.bsc-eoc.org/checklist.jsp?region=LI" },
    { cc: "LT", label: "Ornitologija Observation Portal", url: "https://ornitologija.lt/orni/web/" },
    { cc: "LT", label: "Lithuanian Ornithological Society", url: "https://birdlife.lt/en/" },
    { cc: "LU", label: "ornitho.lu", url: "https://www.ornitho.lu/" },
    { cc: "LU", label: "natur&ëmwelt", url: "https://www.naturemweltasbl.lu/" },
    { cc: "MT", label: "BirdLife Malta", url: "https://birdlifemalta.org/" },
    { cc: "MT", label: "Malta Bird Reports", url: "https://birdlifemalta.org/information/publications/malta-bird-report/" },
    { cc: "MT", label: "Birds of Malta", url: "https://www.birdsofmalta.com/" },
    { cc: "MD", label: "Ornitodata Moldova", url: "https://ornitodata.sppn.md/ornitodata" },
    { cc: "MD", label: "Society for the Protection of Birds and Nature", url: "https://sppn.md/" },
    { cc: "MD", label: "eBird", url: "https://ebird.org/region/MD" },
    { cc: "MC", label: "eBird", url: "https://ebird.org/region/MC" },
    { cc: "MC", label: "Faune-PACA", url: "https://www.faune-paca.org/" },
    { cc: "MC", label: "LPO PACA", url: "https://paca.lpo.fr/" },
    { cc: "ME", label: "Observation.org", url: "https://me.observation.org/" },
    { cc: "ME", label: "CZIP", url: "https://czip.me/en/" },
    { cc: "ME", label: "eBird", url: "https://ebird.org/region/ME" },
    { cc: "NL", label: "Waarneming.nl", url: "https://waarneming.nl/" },
    { cc: "NL", label: "Sovon", url: "https://www.sovon.nl/" },
    { cc: "NL", label: "Vogelbescherming Nederland", url: "https://www.vogelbescherming.nl/" },
    { cc: "NL", label: "Dutch Birding", url: "https://www.dutchbirding.nl/" },
    { cc: "MK", label: "Ptici.mk", url: "https://ptici.mk/" },
    { cc: "MK", label: "Macedonian Ecological Society", url: "https://mes.org.mk/" },
    { cc: "MK", label: "eBird", url: "https://ebird.org/region/MK" },
    { cc: "NO", label: "Artsobservasjoner", url: "https://artsobservasjoner.no/" },
    { cc: "NO", label: "BirdLife Norge", url: "https://www.birdlife.no/" },
    { cc: "NO", label: "BirdLifeData", url: "https://birdlifedata.no/" },
    { cc: "PL", label: "ornitho.pl", url: "https://www.ornitho.pl/" },
    { cc: "PL", label: "eBird", url: "https://ebird.org/region/PL" },
    { cc: "PL", label: "OTOP", url: "https://otop.org.pl/" },
    { cc: "PT", label: "eBird Portugal", url: "https://ebird.org/portugal/home" },
    { cc: "PT", label: "SPEA", url: "https://spea.pt/en/" },
    { cc: "PT", label: "Aves de Portugal", url: "https://www.avesdeportugal.info/" },
    { cc: "RO", label: "Ornitodata", url: "https://ornitodata2.sor.ro/web" },
    { cc: "RO", label: "OpenBirdMaps", url: "https://openbirdmaps.ro/" },
    { cc: "RO", label: "Romanian Ornithological Society", url: "https://www.sor.ro/" },
    { cc: "RU", label: "RU-Birds", url: "https://ru-birds.ru/" },
    { cc: "RU", label: "BirdsRussia", url: "https://birdsrussia.org/" },
    { cc: "RU", label: "eBird", url: "https://ebird.org/region/RU" },
    { cc: "SM", label: "ornitho.it", url: "https://www.ornitho.it/" },
    { cc: "SM", label: "Centro Naturalistico Sammarinese", url: "https://www.istruzioneecultura.sm/pub1/IstruzioneSM/istruzione/Centro-Naturalistico-Sammarinese.html" },
    { cc: "SM", label: "Avibase San Marino", url: "https://avibase.bsc-eoc.org/checklist.jsp?region=SM" },
    { cc: "RS", label: "Observation.org", url: "https://rs.observation.org/" },
    { cc: "RS", label: "Bird Protection and Study Society of Serbia", url: "https://pticesrbije.rs/" },
    { cc: "RS", label: "eBird", url: "https://ebird.org/region/RS" },
    { cc: "SK", label: "Aves-Symfony", url: "https://aves.vtaky.sk/" },
    { cc: "SK", label: "SOS / BirdLife Slovakia", url: "https://www.vtaky.sk/" },
    { cc: "SK", label: "Atlas of Slovak Birds", url: "https://atlas.vtaky.sk/atlasvtakov.php?id=oatlase" },
    { cc: "SI", label: "Atlas ptic", url: "https://atlas.ptice.si/atlas/" },
    { cc: "SI", label: "DOPPS", url: "https://ptice.si/" },
    { cc: "SI", label: "eBird", url: "https://ebird.org/region/SI" },
    { cc: "ES", label: "eBird España", url: "https://ebird.org/spain/home" },
    { cc: "ES", label: "SEO/BirdLife", url: "https://seo.org/" },
    { cc: "ES", label: "Reservoir Birds", url: "https://reservoirbirds.com/" },
    { cc: "ES", label: "ornitho.cat", url: "https://www.ornitho.cat/" },
    { cc: "SE", label: "Artportalen", url: "https://www.artportalen.se/" },
    { cc: "SE", label: "BirdLife Sverige", url: "https://birdlife.se/" },
    { cc: "SE", label: "Checklistan", url: "https://checklista.artportalen.se/" },
    { cc: "SE", label: "Fågelkartan", url: "https://fagelkartan.se/" },
    { cc: "CH", label: "ornitho.ch", url: "https://www.ornitho.ch/" },
    { cc: "CH", label: "Swiss Ornithological Institute", url: "https://www.vogelwarte.ch/en/" },
    { cc: "CH", label: "BirdLife Switzerland", url: "https://www.birdlife.ch/" },
    { cc: "TR", label: "TRAKUS", url: "https://www.trakus.org/en" },
    { cc: "TR", label: "Doğa Derneği", url: "https://www.dogadernegi.org/" },
    { cc: "TR", label: "eBird", url: "https://ebird.org/region/TR" },
    { cc: "UA", label: "UkrBIN", url: "https://www.ukrbin.com/" },
    { cc: "UA", label: "Ukrainian Society for the Protection of Birds", url: "https://www.birdlife.org.ua/en/" },
    { cc: "UA", label: "eBird", url: "https://ebird.org/region/UA" },
    { cc: "GB", label: "BirdTrack", url: "https://www.bto.org/get-involved/volunteer/projects/birdtrack" },
    { cc: "GB", label: "British Trust for Ornithology", url: "https://www.bto.org/" },
    { cc: "GB", label: "RSPB", url: "https://www.rspb.org.uk/" },
    { cc: "GB", label: "BirdGuides", url: "https://www.birdguides.com/" },
    { cc: "VA", label: "eBird", url: "https://ebird.org/region/VA" },
    { cc: "VA", label: "ornitho.it", url: "https://www.ornitho.it/" },
    { cc: "VA", label: "Avibase Vatican City", url: "https://avibase.bsc-eoc.org/checklist.jsp?region=VA" },
    { cc: "CA", label: "Birds Canada", url: "https://www.birdscanada.org/" },
    { cc: "CA", label: "eBird Canada", url: "https://ebird.org/canada/home" },
    { cc: "CA", label: "NatureCounts", url: "https://naturecounts.ca/" },
    { cc: "CA", label: "iNaturalist Canada", url: "https://inaturalist.ca/" },
    { cc: "US", label: "eBird", url: "https://ebird.org/home" },
    { cc: "US", label: "Cornell Lab of Ornithology", url: "https://www.birds.cornell.edu/" },
    { cc: "US", label: "Audubon", url: "https://www.audubon.org/" },
    { cc: "US", label: "American Bird Conservancy", url: "https://abcbirds.org/" },
    { cc: "MX", label: "aVerAves (eBird México)", url: "https://ebird.org/vermexico/home" },
    { cc: "MX", label: "NaturaLista", url: "https://www.naturalista.mx/" },
    { cc: "MX", label: "CIPAMEX", url: "https://cipamex.org/" },
    { cc: "GL", label: "eBird", url: "https://ebird.org/region/GL" },
    { cc: "GL", label: "Observation.org", url: "https://gl.observation.org/" },
    { cc: "BM", label: "eBird", url: "https://ebird.org/region/BM" },
    { cc: "BM", label: "Bermuda Audubon Society", url: "https://www.audubon.bm/" },
    { cc: "BZ", label: "eBird", url: "https://ebird.org/region/BZ" },
    { cc: "BZ", label: "Belize Audubon Society", url: "https://www.belizeaudubon.org/" },
    { cc: "CR", label: "eBird", url: "https://ebird.org/region/CR" },
    { cc: "CR", label: "Unión de Ornitólogos de Costa Rica", url: "https://uniondeornitologos.com/" },
    { cc: "SV", label: "eBird", url: "https://ebird.org/region/SV" },
    { cc: "SV", label: "Observation.org", url: "https://sv.observation.org/" },
    { cc: "GT", label: "eBird", url: "https://ebird.org/region/GT" },
    { cc: "GT", label: "Observation.org", url: "https://gt.observation.org/" },
    { cc: "HN", label: "eBird", url: "https://ebird.org/region/HN" },
    { cc: "HN", label: "Observation.org", url: "https://hn.observation.org/" },
    { cc: "NI", label: "eBird", url: "https://ebird.org/region/NI" },
    { cc: "NI", label: "Observation.org", url: "https://ni.observation.org/" },
    { cc: "PA", label: "eBird", url: "https://ebird.org/region/PA" },
    { cc: "PA", label: "Panama Audubon Society", url: "https://www.audubonpanama.org/" },
    { cc: "AU", label: "eBird Australia", url: "https://ebird.org/australia/home" },
    { cc: "AU", label: "BirdLife Australia", url: "https://birdlife.org.au/" },
    { cc: "AU", label: "Birdata", url: "https://birdata.birdlife.org.au/" },
    { cc: "AU", label: "Atlas of Living Australia", url: "https://www.ala.org.au/" },
    { cc: "NZ", label: "eBird New Zealand", url: "https://ebird.org/newzealand/home" },
    { cc: "NZ", label: "Birds New Zealand", url: "https://www.birdsnz.org.nz/" },
    { cc: "NZ", label: "New Zealand Birds Online", url: "https://www.nzbirdsonline.org.nz/" },
    { cc: "NZ", label: "iNaturalist NZ", url: "https://inaturalist.nz/" },
    { cc: "PG", label: "eBird", url: "https://ebird.org/region/PG" },
    { cc: "PG", label: "Observation.org", url: "https://pg.observation.org/" },
    { cc: "FJ", label: "eBird", url: "https://ebird.org/region/FJ" },
    { cc: "FJ", label: "NatureFiji-MareqetiViti", url: "https://naturefiji.org/" },
    { cc: "SB", label: "eBird", url: "https://ebird.org/region/SB" },
    { cc: "SB", label: "Observation.org", url: "https://sb.observation.org/" },
    { cc: "VU", label: "eBird", url: "https://ebird.org/region/VU" },
    { cc: "VU", label: "Observation.org", url: "https://vu.observation.org/" },
    { cc: "NC", label: "eBird", url: "https://ebird.org/region/NC" },
    { cc: "NC", label: "Observation.org", url: "https://nc.observation.org/" },
    { cc: "PF", label: "eBird", url: "https://ebird.org/region/PF" },
    { cc: "PF", label: "SOP Manu", url: "https://www.manu.pf/" },
    { cc: "WS", label: "eBird", url: "https://ebird.org/region/WS" },
    { cc: "TO", label: "eBird", url: "https://ebird.org/region/TO" },
    { cc: "GU", label: "eBird", url: "https://ebird.org/region/GU" },
    { cc: "PW", label: "eBird", url: "https://ebird.org/region/PW" },
    { cc: "PW", label: "Palau Conservation Society", url: "https://www.palauconservation.org/" },
    { cc: "FM", label: "eBird", url: "https://ebird.org/region/FM" },
    { cc: "KI", label: "eBird", url: "https://ebird.org/region/KI" },
    { cc: "MH", label: "eBird", url: "https://ebird.org/region/MH" },
    // Worldwide (WLD) — global sites, shown for every country alongside its continent.
    { cc: "WLD", label: "eBird", url: "https://ebird.org/" },
    { cc: "WLD", label: "Observation.org", url: "https://observation.org/" },
    { cc: "WLD", label: "iNaturalist", url: "https://www.inaturalist.org/" },
    { cc: "WLD", label: "GBIF", url: "https://www.gbif.org/" },
    { cc: "WLD", label: "Avibase", url: "https://avibase.bsc-eoc.org/" },
    { cc: "WLD", label: "BirdLife DataZone", url: "https://datazone.birdlife.org/" },
    { cc: "WLD", label: "xeno-canto", url: "https://xeno-canto.org/" },
    // Europe (EU) — continent-specific, shown only for European countries.
    { cc: "EU", label: "EuroBirdPortal", url: "https://www.eurobirdportal.org/" },
    { cc: "EU", label: "European Breeding Bird Atlas 2", url: "https://ebba2.info/" },
    { cc: "EU", label: "BirdLife Europe and Central Asia", url: "https://www.birdlife.org/europe-and-central-asia/" },
    { cc: "EU", label: "Birdingplaces.eu", url: "https://www.birdingplaces.eu/" },
    { cc: "EU", label: "Trektellen", url: "https://www.trektellen.org/" },
    // Americas (AME) — shown for North & Central American countries.
    { cc: "AME", label: "American Ornithological Society", url: "https://americanornithology.org/" },
    { cc: "AME", label: "Partners in Flight", url: "https://partnersinflight.org/" },
    { cc: "AME", label: "Neotropical Birds (Birds of the World)", url: "https://birdsoftheworld.org/bow/home" }
  ];
window.AppStaticData.COUNTRY_NAMES = {
    WLD: "Worldwide", EU: "Europe", AME: "Americas", OCE: "Oceania",
    AL: "Albania", AD: "Andorra", AM: "Armenia", AT: "Austria", AZ: "Azerbaijan", BY: "Belarus",
    BE: "Belgium", BA: "Bosnia and Herzegovina", BG: "Bulgaria", HR: "Croatia", CY: "Cyprus",
    CZ: "Czechia", DK: "Denmark", EE: "Estonia", FI: "Finland", FR: "France", GE: "Georgia",
    DE: "Germany", GR: "Greece", HU: "Hungary", IS: "Iceland", IE: "Ireland", IT: "Italy",
    KZ: "Kazakhstan", XK: "Kosovo", LV: "Latvia", LI: "Liechtenstein", LT: "Lithuania",
    LU: "Luxembourg", MT: "Malta", MD: "Moldova", MC: "Monaco", ME: "Montenegro",
    NL: "Netherlands", MK: "North Macedonia", NO: "Norway", PL: "Poland", PT: "Portugal",
    RO: "Romania", RU: "Russia", SM: "San Marino", RS: "Serbia", SK: "Slovakia", SI: "Slovenia",
    ES: "Spain", SE: "Sweden", CH: "Switzerland", TR: "Turkey", UA: "Ukraine",
    GB: "United Kingdom", VA: "Vatican City",
    CA: "Canada", US: "United States", MX: "Mexico", GL: "Greenland", BM: "Bermuda",
    BZ: "Belize", CR: "Costa Rica", SV: "El Salvador", GT: "Guatemala", HN: "Honduras",
    NI: "Nicaragua", PA: "Panama",
    AU: "Australia", NZ: "New Zealand", PG: "Papua New Guinea", FJ: "Fiji",
    SB: "Solomon Islands", VU: "Vanuatu", NC: "New Caledonia", PF: "French Polynesia",
    WS: "Samoa", TO: "Tonga", GU: "Guam", PW: "Palau", FM: "Micronesia",
    KI: "Kiribati", MH: "Marshall Islands"
  };
window.AppStaticData.BUILTIN_BLOGS = {
    GB: [ { label: "Brian's Birding Blog", url: "https://briansbirding.blogspot.com/" }, { label: "Austin's Birding Blog", url: "https://austinmorley.blogspot.com/" }, { label: "Non-Stop Birding (Peter Alfrey)", url: "https://peteralfreybirdingnotebook.blogspot.com/" } ],
    IE: [ { label: "NI Birds", url: "https://nibirds.blogspot.com/" }, { label: "The Irish Bird Blog", url: "https://theirishbirdblog.com/" } ],
    NL: [ { label: "Weblog Robert van der Meer", url: "https://robertbirding.wordpress.com/" } ],
    NO: [ { label: "Øygarden Birding", url: "http://oeygardenbirds.blogspot.com/" }, { label: "Utsira as Way of Life", url: "http://atgrims.blogspot.com/" } ],
    FI: [ { label: "Finnish Birding", url: "http://lintuja-sunmuita.blogspot.com/" }, { label: "High Latitude Birder (Olli Haukkovaara)", url: "https://highlatitudebirder.blogspot.com/" } ],
    DE: [ { label: "Vogelguckerin", url: "https://vogelguckerin.de/blog/" } ],
    ES: [ { label: "Birding in Spain's Wild West", url: "https://birdinginspainswildwest.com/" } ],
    FO: [ { label: "Birding Faroes", url: "https://birdingfaroes.wordpress.com/" } ]
  };
window.AppStaticData.FB_COUNTRY = {
    AD:"europe/principality-of-andorra",AL:"europe/albanian-republic",AM:"europe/republic-of-armenia",
    AR:"south-america/argentine-republic",AT:"europe/republic-of-austria",AU:"oceania/commonwealth-of-australia",
    AZ:"europe/republic-of-azerbaijan",BA:"europe/bosnia-and-herzegovina",BE:"europe/kingdom-of-belgium",
    BG:"europe/republic-of-bulgaria",BO:"south-america/plurinational-state-of-bolivia",
    BR:"south-america/federative-republic-of-brazil",BW:"africa/republic-of-botswana",
    BY:"europe/republic-of-belarus",CA:"north-america/canada",CL:"south-america/republic-of-chile",
    CN:"asia/peoples-republic-of-china",CO:"south-america/republic-of-colombia",
    CY:"europe/republic-of-cyprus",CZ:"europe/czech-republic",DE:"europe/federal-republic-of-germany",
    DK:"europe/kingdom-of-denmark",EC:"south-america/republic-of-ecuador",EE:"europe/republic-of-estonia",
    EG:"africa/arab-republic-of-egypt",ES:"europe/kingdom-of-spain",
    ET:"africa/federal-democratic-republic-of-ethiopia",FI:"europe/republic-of-finland",
    FR:"europe/french-republic",GB:"europe/united-kingdom",GE:"europe/georgia",
    GI:"europe/gibraltar",GR:"europe/hellenic-republic",HR:"europe/republic-of-croatia",
    HU:"europe/hungary",ID:"asia/republic-of-indonesia",IE:"europe/irish-republic",
    IL:"asia/state-of-israel",IN:"asia/republic-of-india",IR:"asia/islamic-republic-of-iran",
    IS:"europe/iceland",IT:"europe/italian-republic",JP:"asia/japan",
    KE:"africa/republic-of-kenya",KR:"asia/republic-of-korea",
    LI:"europe/principality-of-liechtenstein",LT:"europe/lithuania",
    LU:"europe/grand-duchy-of-luxembourg",LV:"europe/republic-of-latvia",
    MA:"africa/kingdom-of-morocco",MC:"europe/principality-of-monaco",
    MD:"europe/republic-of-moldova",ME:"europe/montenegro",
    MK:"europe/republic-of-north-macedonia",MT:"europe/republic-of-malta",
    MX:"north-america/united-mexican-states",MY:"asia/malaysia",
    NA:"africa/republic-of-namibia",NL:"europe/netherlands",
    NO:"europe/kingdom-of-norway",NZ:"oceania/new-zealand",
    PE:"south-america/republic-of-peru",PH:"asia/republic-of-the-philippines",
    PL:"europe/republic-of-poland",PT:"europe/portuguese-republic",
    RO:"europe/romania",RS:"europe/republic-of-serbia",
    RU:"europe/russian-federation",SA:"asia/kingdom-of-saudi-arabia",
    SE:"europe/kingdom-of-sweden",SG:"asia/republic-of-singapore",
    SI:"europe/republic-of-slovenia",SK:"europe/slovak-republic",
    SM:"europe/republic-of-san-marino",TH:"asia/kingdom-of-thailand",
    TR:"europe/republic-of-turkey",TZ:"africa/united-republic-of-tanzania",
    UA:"europe/ukraine",UG:"africa/republic-of-uganda",
    AE:"asia/united-arab-emirates",US:"north-america/united-states-of-america",
    VE:"south-america/bolivarian-republic-of-venezuela",
    VN:"asia/socialist-republic-of-vietnam",ZA:"africa/republic-of-south-africa"
  };
